#Circulants

In [2]:
import numpy as np

#Function to generate our 'w' (stupidly called A here!). It has n columns
#and r 1s in each row. Each query has l new paramters (dropping l old ones)
#so in effect the 1s are shifted by l each time.
#for example n=6, r=2, l=2 gives:
#      [[ 1.,  1.,  0.,  0.,  0.,  0.],
#       [ 0.,  0.,  1.,  1.,  0.,  0.],
#       [ 0.,  0.,  0.,  0.,  1.,  1.]]
#the function returns A, and the AA^T
#maybe it should be worrying about A^T A but for l=1 these are equal...?
#It also returns the determinant of this.
def calc_circulant(n,r,l):
    #n = matrix size
    #r = row width
    #l = overlap step (how many items don't overlap)
    if (n % l)!=0:
        raise ValueError('The length of the overlap step (%d) is not a factor of the matrix width (%d).' % (l,n))
    nrows = n/l
    a = np.zeros(n)
    a[0:r] = 1
    A = np.zeros((nrows,n))
    for i in range(nrows):
        A[i,:] = a
        a = np.roll(a,l)
    AAt = np.dot(A,A.transpose())
    det = np.linalg.det(AAt)
    return A, AAt, det

#For l=1, this uses the \prod_j^(n-1) r+ \sum_k=1^(r-1) 2k cos (2\pi k j / n) fn to find the determinant
def calc_quick(n,r,l):
    if l!=1:
        raise ValueError('This algorithm only works for l=1')
    T = 1
    for j in range(n):
        S = 0
        for k in range(1,r):
            temp = 2*(r-k)*np.cos(2*np.pi*j*k/n)
            S+=temp
        S = S + r
        T *= S
    return T

#finds the greatest common denominator
def gcd(a, b):
    return a if b == 0 else gcd(b, a % b)

#for l=1 (I've not investigated l>1), uses the observations about n and r and the determinant.
#(Is there a quick way of saying if the gca=1 without having to run the algorithm?
def calc_super_quick(n,r,l):
    if l!=1:
        raise ValueError('This algorithm only works for l=1')    
    if gcd(n,r)!=1:
        return 0
    else:
        return r**2
#I wonder if this gives us an alternative way to find the GCD of a pair of numbers????

#A failed attempt to use a trig id to remove the summation from the earlier equation. Ignore.
def calc_very_quick(n,r,l):
    if l!=1:
        raise ValueError('This algorithm only works for l=1')
    T = 1
    #for j = 0
    T = r + 2*((r-1)**2/2) + (r-1)/2
    for j in range(1,n):
        S = r - np.sin(2*np.pi*r*j/n) * np.cos((r-1)*np.pi*j/n) / np.sin(np.pi*j/n)
        T *= S
    return T

l = 1
n = 7
r = 2
guess = calc_super_quick(n,r,l) #only works if l=1
A, AAt, det = calc_circulant(n,r,l)
print "Determinants"
print "Actual %0.2f" % det
print "Guess  %0.2f" % guess
print "Our original W matrix (this is what you need to make your program work)"
print A
print "Times its transpose"
print AAt

Determinants
Actual 4.00
Guess  4.00
Our original W matrix (this is what you need to make your program work)
[[ 1.  1.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  1.]]
Times its transpose
[[ 2.  1.  0.  0.  0.  0.  1.]
 [ 1.  2.  1.  0.  0.  0.  0.]
 [ 0.  1.  2.  1.  0.  0.  0.]
 [ 0.  0.  1.  2.  1.  0.  0.]
 [ 0.  0.  0.  1.  2.  1.  0.]
 [ 0.  0.  0.  0.  1.  2.  1.]
 [ 1.  0.  0.  0.  0.  1.  2.]]
